spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: naveenkokkiligadda2001@gmail.com
    password: kpga uemk mbfy sveh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

