spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: <YOUR EMAIL>
    password: <APP PASSWORD>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

